#!/usr/bin/env bash
# A bash script which transfers a file from a client to server

# Check if correct number of parameters provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file=$1
ip_address=$2
username=$3
path_to_ssh_key=$4

# Transfer file using scp command
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip_address:~/"

# Check if file transfer was successful
if [ $? -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
  exit 1
fi

